// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serve

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-Hermes/app/user/internal/biz"
	"go-Hermes/app/user/internal/conf"
	"go-Hermes/app/user/internal/dao"
	"go-Hermes/app/user/internal/data/user"
	"go-Hermes/app/user/internal/server"
	"go-Hermes/app/user/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	daoDAO, cleanup, err := dao.NewDao(data, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := user.NewUserRepo(daoDAO, data, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
