// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serve

import (
	"akita/quantum_cat/app/sms/internal/biz"
	"akita/quantum_cat/app/sms/internal/conf"
	"akita/quantum_cat/app/sms/internal/dao"
	"akita/quantum_cat/app/sms/internal/data/sms"
	"akita/quantum_cat/app/sms/internal/server"
	"akita/quantum_cat/app/sms/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	daoDAO, cleanup, err := dao.NewDao(data, logger)
	if err != nil {
		return nil, nil, err
	}
	smsRepo := sms.NewUserRepo(daoDAO, data, logger)
	smsUseCase := biz.NewSmsUseCase(smsRepo, logger)
	smsService := service.NewUserService(smsUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, smsService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
